### ISSUE TITLE
youtube-dl use by a googler?

### ISSUE THREAD

**Issue by DoWhileGeek** [EliRibble/youtube-dl-music-library#1]
is that even legal? 😛

edit:
RIP google play music

**Comment by EliRibble** [comment]
Ug, yeah, don't even get me started on Google Play Music disappearing. The whole thing makes me furious. Google Play Music was actually a decent product and worked well with Google smart speakers. Then crap happened internal to Google and Play Music got killed in favor of Youtube Music. It barely works with smart speakers, and is nearly impossible to block on smart displays entirely without building incredibly complex network-level systems for detecting traffic.

So, yes, in case you were wondering, this project is a manifestation of my fury towards this whole situation. I'm taking my music, my ball, and going home.

**Comment by DoWhileGeek** [comment]
Sorry for the late reply, but yea, GPM was easily the best audio service I've ever used, was really sad to see it go.

Anywho, nice to talk to ya! 👋
